Repository GhostPangPang/GhostPong, pull requests merged in 2023-08, with the labels that each got.

#586 ✨ [Feature] footer 컴포넌트
  frontend/.pnp.cjs
  frontend/.pnp.loader.mjs
  frontend/.yarn/sdks/prettier/index.js
  frontend/package.json
  frontend/src/assets/svgs/ghost-sm.svg
  frontend/src/layout/Footer/Footer.tsx
Labels: enhancement, frontend

#591 🐛 [Bugfix] Fix userInfo sync error
  frontend/src/ProtectedRoute.tsx
  frontend/src/SocketHandler.tsx
  frontend/src/common/ProgressBar/ProgressBar.tsx
  frontend/src/common/ProgressBar/RankProgressBar/RankProgressBar.tsx
  frontend/src/hooks/auth/useAuth.tsx
  frontend/src/hooks/channel/index.ts
  frontend/src/hooks/channel/useChat.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/user/index.ts
  frontend/src/hooks/user/useProfileData.tsx
  frontend/src/hooks/user/useUserInfo.tsx
  frontend/src/layout/GameLayout/GameSideBar.tsx
  frontend/src/layout/Header/Header.tsx
  frontend/src/libs/utils/itemgenerator.tsx
  frontend/src/pages/EditProfilePage/EditProfilePage.tsx
  frontend/src/pages/GameListPage/GameContent/GameContent.tsx
  frontend/src/pages/GameListPage/GameHeader/GameCreateModal/GameCreateModal.tsx
  frontend/src/pages/GameListPage/GameHeader/GameHeader.tsx
  frontend/src/pages/GameLoadingPage/GameLoadingPage.tsx
  frontend/src/pages/GamePage/GamePage.tsx
  frontend/src/pages/GamePage/GameResultModal/GameResultModal.tsx
  frontend/src/pages/GameReadyPage/ChatBox/ChatInput.tsx
  frontend/src/pages/GameReadyPage/GameReadyPage.tsx
  frontend/src/pages/GameReadyPage/ObserverBox/ObserverBox.tsx
  frontend/src/pages/GameReadyPage/RoomInfo/RoomInfo.tsx
  frontend/src/pages/GameReadyPage/SettingModal/SettingModal.tsx
  frontend/src/pages/GameReadyPage/Versus/Versus.tsx
  frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
  frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
  frontend/src/pages/MessagePage/Message/Message.tsx
  frontend/src/pages/MessagePage/Message/MessageContent.tsx
  frontend/src/pages/MessagePage/Message/MessageInput.tsx
  frontend/src/pages/MessagePage/MessageList/MessageList.tsx
  frontend/src/pages/MessagePage/MessageList/MessageListItem.tsx
  frontend/src/pages/ProfilePage/HistoryBox/HistoryBox.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
Labels: bug, enhancement, frontend

#594 :hammer: [Refactor] Change ci branch to develop
  .github/workflows/chromatic.yml
  .github/workflows/frontend-build.yml
Labels: frontend, refactoring

#595 🔨 [Refactor] prepage 리팩토링
  frontend/src/assets/svgs/42.svg
  frontend/src/assets/svgs/github-sm.svg
  frontend/src/assets/svgs/google.png
  frontend/src/assets/svgs/google.svg
  frontend/src/common/Button/GameButton.tsx
  frontend/src/common/Input/GameInput.tsx
  frontend/src/pages/PrePage/PrePage.tsx
  frontend/src/pages/RegisterPage/RegisterPage.tsx
  frontend/src/pages/TwoFactorLoginPage/TwoFactorLoginPage.tsx
Labels: enhancement, frontend, refactoring

#597 💚 [Chore] development 및 production 환경 env 파일 분리
  .dockerignore
  .env.example
  .gitignore
  backend/.env.example
  backend/docker-compose.dev.yml
  backend/package.json
  backend/seeding/data-source.ts
  backend/seeding/reset-db.sh
  backend/seeding/seeder/message.seeder.ts
  backend/src/config/app/configuration.module.ts
  backend/src/config/database/configuration.module.ts
  backend/src/config/database/configuration.ts
  docker-compose.yml
Labels: enhancement

#602 :memo: docs: Update README.md
  README.md
Labels: documentation

#603 :memo: docs: Update README.md
  README.md
Labels: documentation

#605 ✨ [Feature] Update docker-cd.yml
  .github/workflows/docker-cd.yml
  backend/.gitignore
  docker-compose.yml
  frontend/src/assets/svgs/github.svg
  frontend/src/assets/svgs/google.png
  frontend/src/pages/PrePage/PrePage.tsx
Labels: enhancement

#607 🐛 [Hotfix] Add dockerignore
  .dockerignore
  .gitignore
  backend/.dockerignore
Labels: bug

#609 🐛 [Hotfix] Update docker cd
  .github/workflows/docker-cd.yml
Labels: bug, enhancement

#612 🐛 [Hotfix] Update docker cd
  .github/workflows/docker-cd.yml
Labels: bug

#614 :bug: [HotFix] Fix docker-cd.yml
  .github/workflows/docker-cd.yml
  frontend/Dockerfile
  frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
  frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
Labels: bug

#617 ✨ [Feature] Update docker-cd.yml
  .github/workflows/docker-cd.yml
  README.md
  frontend/Dockerfile
  frontend/src/assets/svgs/google.png
  frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
  frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
Labels: bug, enhancement

#618 ♻️ [Release] release sprint13
  .github/workflows/docker-cd.yml
  frontend/Dockerfile
  frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
  frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
Labels: release

#619 ✨ [Feature] DB migration
  .dockerignore
  backend/db/migrations/1692710671031-migration.ts
  backend/db/migrations/orm-config.ts
  backend/db/seeding/data-source.ts
  backend/db/seeding/factory/auth.factory.ts
  backend/db/seeding/factory/frieindship.factory.ts
  backend/db/seeding/factory/game-history.factory.ts
  backend/db/seeding/factory/message.factory.ts
  backend/db/seeding/factory/user.factory.ts
  backend/db/seeding/reset-db.sh
  backend/db/seeding/seeder/message.seeder.ts
  backend/package.json
  backend/src/auth/auth.service.ts
  backend/src/config/database/configuration.service.ts
  backend/src/entity/auth.entity.ts
Labels: enhancement, backend

#621 🔨 [Refactor] Change to distinguish users by account ID
  backend/src/auth/auth.service.ts
  backend/src/auth/strategy/ft.strategy.ts
  backend/src/auth/strategy/google.strategy.ts
  backend/src/auth/type/login-info.ts
  backend/src/config/database/configuration.service.ts
  backend/src/entity/auth.entity.ts
Labels: backend, refactoring

#622 ✨ [Feature] Github OAuth
  backend/.env.example
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/guard/ft.guard.ts
  backend/src/auth/guard/google.guard.ts
  backend/src/auth/guard/social.guard.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/config/auth/github/configuration.module.ts
  backend/src/config/auth/github/configuration.service.ts
  backend/src/config/auth/github/configuration.ts
  backend/src/user/user.module.ts
  backend/yarn.lock
  frontend/src/pages/PrePage/PrePage.tsx
Labels: enhancement, backend

#623 :sparkles: [Feature] Update login/signup pages
  frontend/src/App.tsx
  frontend/src/pages/MessagePage/BlockModal/BlockModal.tsx
  frontend/src/pages/MessagePage/FriendsModal/FriendsModal.tsx
  frontend/src/pages/SignInPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/index.ts
Labels: enhancement

#624 ✨ [Feature] Local login/signup API
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/request/local-login-request.dto.ts
  backend/src/auth/dto/request/local-signup-request.dto.ts
  backend/src/auth/strategy/local.strategy.ts
  backend/src/auth/type/login-response-options.ts
  backend/yarn.lock
  frontend/src/pages/PrePage/PrePage.tsx
  frontend/src/pages/SignInPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  types/auth/request/index.ts
  types/auth/request/local-login-request.interface.ts
  types/auth/request/local-signup-request.interface.ts
Labels: enhancement, backend

#627 🐛 [HotFix] Register Alert error
  frontend/src/pages/SignUpPage/index.tsx
Labels: bug
